---
name: CI
# yamllint disable-line rule:truthy
on:
  [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: sudo ./build.sh

      - name: print sha256sum
        run: cat output/sha256

      - name: Generate Tag
        id: tag
        run: |
          VER=$(egrep ^KERNEL_VERSION build.sh|cut -d= -f2)
          echo Version is $VER
          echo "::set-output name=tag::${VER}"
          sed -i "s/KERNEL_VERSION/${VER}/g" \
          ${{ github.workspace }}/.github/workflows/put_iso_back.txt

      - name: Upload iso artifact
        uses: actions/upload-artifact@v2
        with:
          name: mbp-ubuntu-${{ steps.tag.outputs.tag }}
          path: ${{ github.workspace }}/output/*

      - name: Release
        if: github.ref == 'refs/heads/kubuntu'
        uses: softprops/action-gh-release@v1
        with:
          #files: ${{ github.workspace }}/*.iso
          files: ${{ github.workspace }}/output/*
          tag_name: kubuntu-20.04-${{ steps.tag.outputs.tag }}
          body_path: ${{ github.workspace }}/.github/workflows/put_iso_back.txt
          draft: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
